### ISSUE TITLE
kitcoin关注

### ISSUE THREAD

**Issue by wangyanzhuo333** [lovubuntu/kitcoin#1]
k币国外关注度看来不高啊！

**Comment by wangyanzhuo333** [comment]
imho scam coin
https://bitcointalk.org/index.php?topic=1972151.0

**Comment by lovubuntu** [comment]
I can't stop laughing. 

<a href="https://www.youtube.com/watch?v=omApdPl0ovI&feature=youtu.be&t=18&autoplay=1" target="_blank"><img src="http://img.youtube.com/vi/omApdPl0ovI/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

Anyway I've added a Readme file and hope that helps.
